### ISSUE TITLE
Handlers not registered

### ISSUE THREAD

**Issue by bfreuden** [eraga/vue-vertx3-eventbus-client#1]
Hi,
Since it is my first message here, first Id' like to thank you for creating vue-vertx3-eventbus-client!
I have a problem with handlers not being registered when using vue-vertx3-eventbus-client.
The problem seems to come from this line:
handlersToReg.concat(handlers)
According to [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) it seems that the concat function does not modify the arrays but is returning a new array.
I modified the code a little bit:
handlersToReg = handlersToReg.concat(handlers)
and now it seems to work.
Unfortunately I'm no Javascript expert so maybe I'm wrong. I will issue a PR just in case, feel free to reject it.

**Comment by tntclaus** [comment]
@bfreuden thank you for the report and the fix. I will test it today.
